export const CLEAR_HANDLER = "CLEAR_HANDLER";
export const NUMBER_CLICK = "NUMBER_CLICK";
export const EQUAL_HANDLER = "EQUAL_HANDLER";
export const DISABLE_HANDLER = "DISABLE_HANDLER";
export const DOUBLE_OPERATORS = "DOUBLE_OPERATORS";
